version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cleanbreath-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DEFAULT_SCHEMA=${DEFAULT_SCHEMA}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - cleanbreath-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/v1/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
