server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOSTNAME}/${DEFAULT_SCHEMA}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    web:
      pageable:
        default-page-size: 20

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

batch:
  promotion:
    threshold: 20 # 임계값 20으로 수정
    cron: "0 0 3 * * *"

management:
  endpoints:
    web:
      exposure:
        include: health, info, monitoring, metrics
