server:
  port: 7000

spring:
  application:
    name: cleanbreath-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CleanBreath?serverTimezone=Asia/Seoul
    username: root
    password: Dnfltkfkd0306

  jpa:
    hibernate:
      ddl-auto: none

