package cleanbreath.backend.entity;

public enum DivisionArea {
    NON_SMOKING_ZONE,
    SMOKING_ZONE_OPEN_IMPLICIT,
    SMOKING_ZONE_OPEN,
    SMOKING_ZONE_CLOSE_IMPLICIT,
    SMOKING_ZONE_CLOSE,
    SMOKING_ZONE_LINE_IMPLICIT,
    SMOKING_ZONE_LINE
}
